[package]
name = "flux-platform"
version = "1.2.0"
description = "Flux Platform"
authors = ["F0RLE"]
edition = "2021"

[lib]
name = "flux_platform_lib"
path = "src/lib.rs"

[dependencies]
tauri = { version = "2.1.0", features = ["image-ico", "image-png"] }
tauri-plugin-shell = "2.1.0"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
log = "0.4"
env_logger = "0.11"
thiserror = "2.0"
windows-sys = { version = "0.52", features = ["Win32_System_JobObjects", "Win32_System_Threading", "Win32_Foundation"] }
dirs = "5.0"
once_cell = "1.19"
sysinfo = "0.32"
chrono = { version = "0.4", features = ["serde"] }
reqwest = { version = "0.12", features = ["json", "stream"] }
tokio = { version = "1.36", features = ["full"] }
futures-util = "0.3"
indexmap = { version = "1.9", features = ["std", "serde-1"] }

[build-dependencies]
tauri-build = { version = "2.1.0", features = [] }
